### ISSUE TITLE
Deprecated constants warning

### ISSUE THREAD

**Issue by systematicallyrandom** [pnbruckner/ha-life360#18]
Logger: homeassistant.const
Source: helpers/deprecation.py:206
First occurred: 1:58:06 PM (4 occurrences)
Last logged: 1:58:06 PM

LENGTH_FEET was used from life360, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.FEET instead, please report it to the author of the 'life360' custom integration
LENGTH_KILOMETERS was used from life360, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please report it to the author of the 'life360' custom integration
LENGTH_METERS was used from life360, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please report it to the author of the 'life360' custom integration
LENGTH_MILES was used from life360, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead, please report it to the author of the 'life360' custom integration

**Comment by pnbruckner** [comment]
What version are you using? 0.3.10 is easy too old. Please use the much newer beta, 0.5.0b7.

**Comment by systematicallyrandom** [comment]
Great catch. I had literally just updated to the latest beta 0.5.0b7 via
hacs, then rebooted as required and was still getting the same error. After
your suggestion I double checked the version and it was still on 0.3.10.
(Maybe a hacs bug when switching on the beta switch?) I updated again and
this time it actually updated to 0.5.0b7 and that error went away.

Now I'm having other issues, but I'll start another issue if I can't figure
it out. Thanks!
