### ISSUE TITLE
Should we update from v0.5.b07 to master release? (QUESTION)

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [pnbruckner/ha-life360#20]
@pnbruckner As the subject says should we update from v0.5.0b7 to master (v0.5.0)?

**Comment by pnbruckner** [comment]
Yes. There are no functional changes between 0.5.0b7 & 0.5.0. It's just no longer a beta anymore.

**Comment by smarthomefamilyverrips** [comment]
> Yes. There are no functional changes between 0.5.0b7 & 0.5.0. It's just no longer a beta anymore.

Can I use HACS for this when I previously added the integration manually? If i check HACS I not see any versions or other information, the below is all I see.

![2024-05-28_19-00-06](https://github.com/pnbruckner/ha-life360/assets/97987488/ded8ffd2-7e41-42c0-af2f-e2cc3a47a67a)

**Comment by smarthomefamilyverrips** [comment]
@pnbruckner I just did create the custom folder and copied the raw files into it, but if I select "update Information" nothing changes on my screen, also I not have the option "redownload" in the 3 dots menu, but this is probably because i never did download it through HACS yes (as you can see I still have the download button on lower right)

**Comment by pnbruckner** [comment]
Yep, I just noticed that. Click the download button and follow the normal HACS install method.

**Comment by smarthomefamilyverrips** [comment]
> Yep, I just noticed that. Click the download button and follow the normal HACS install process.
> 
> Hopefully it won't complain about the folder already existing, and will simply overwrite it.

@pnbruckner I did do the install through HACS and all good, now running v0.5.0 👍

Thanks for your work and finding the energy to still pick this up again even while they not make it easy on you from the side of life360 💯

I will keep testing the integration and will let you know if any issues pop-up.

I will not close this issue at this moment maybe it helps others that have same question. Of course if you prefer to close it feel free to do so as for me it is solved.
