### ISSUE TITLE
Sign In using Access Type & Token

### ISSUE THREAD

**Issue by stevewrightnz** [pnbruckner/ha-life360#21]
When using the Access Type & Token method the https://app.life360.com/login page only gives options to enter USA phone numbers.

**Comment by pnbruckner** [comment]
Ok. Remember, the feature that allows one to enter the authorization strings directly is really just a work around for when logging in with a password doesn't work.

How do you log into the Life360 app? Do you use a password, and if so, with what type of "username" (email, phone number, ...???)

If you can log into the Life360 app using a password (with whatever username it accepts), can you try those same credentials with the HA integration? Does that work for you?

If not, using that login link, can you find a way to log in successfully? If so, then maybe the same technique can work for you (i.e., finding the access token.)

If you can't log in using a password, and that link doesn't work for you, can you find a different link via Life360's help center?

**Comment by stevewrightnz** [comment]
OK!! figured it out.

Had a real issue with the password for the email method.

Once that was sorted then following the instructions worked. (the info was in {;} token.json)

Thanks
SteveW

**Comment by pnbruckner** [comment]
So, were you able to log in, either via the app, an URL or in the HA integration, using a password? When you finally got the token, how did you get it (i.e., what link did you use)?

**Comment by stevewrightnz** [comment]
Yes I managed to log in using a password after a few tries.  The token was in the {;} token.json entry as per the integration instructions.

I can probably replicate and provide some detailed instructions if you would like?

SteveW

**Comment by pnbruckner** [comment]
If you were able to log in using a password, then why didn't you use that with the integration? Then you wouldn't need to retrieve the token.

**Comment by stevewrightnz** [comment]
Because I couldn't make the password work at the start and I went down the token path.

**Comment by pnbruckner** [comment]
Ok. Yes, if you have any details about how you got the token, that would be appreciated.

**Comment by stevewrightnz** [comment]
Hi Phil

I've replicated the steps here and this seems to be repeatable:-

- Open a browser (I used Chrome for this - It works using Brave too!)
- Three dots in top right corner of the browser
- Choose the "More Tools" option
- Choose the "Developer Tools" option
- In the Developers Tools panel select the "Network" tab
- Go to app.life360.com on the same browser tab.
- Choose email option on the login screen - I didn't try the phone number option as I could only use a US one and I'm in NZ
- Enter your login email
- Enter your password
- In the "Name" area of the "Developer Tools" panel find the "{;} token.json" entry and select it.  (sorting by the "Name" put it towards the top for me (second item))
- In the developers tools panel find the “Preview” tab or the “Response” tab
- The access_token and token_type are in both of these tabs – The “Preview” tab is easier and is fairly self explanatory.
- copy and paste the access token into the HA integration setup panel (check the token type is Bearer)

Hope that helps!

Steve

**Comment by pnbruckner** [comment]
Thanks. But that's basically the same URL & procedure that is already documented. Also, if you're able to log into Life360 using your email & password, then you should be able to use those with the Life360 HA integration as well. No need to use this procedure at all. Although, since you already have it working that way, probably not worth changing.
