### ISSUE TITLE
Does not appear in Integrations

### ISSUE THREAD

**Issue by XGT1977** [pnbruckner/ha-life360#26]
Does not appear in Integrations for 2024.6

**Comment by pnbruckner** [comment]
Please provide more detail. It is not clear what you are asserting.

**Comment by pnbruckner** [comment]
@XGT1977 do you have any more details you can provide?

**Comment by Bosty01** [comment]
I'll jump in here. I have 2024.6.4 and the life360 integration does not show in HACS. When I click the blue button, I get this message: 

ERROR This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

Any ideas?

**Comment by pnbruckner** [comment]
No update from OP.
