### ISSUE TITLE
Images not showing in iOS

### ISSUE THREAD

**Issue by olafvdg** [pnbruckner/ha-life360#27]
Images of the life360 members are showing normally on Android and in browser. However, not in the iOS HA app. Seems specific to this life360 integration....

**Comment by pnbruckner** [comment]
I think I've heard something like this before, but I don't know why this could be.

If you look at the `device_tracker` entity on the STATES page of Developer Tools, does it have an `entity_picture` attribute? If so, if you copy the URL into a browser, does the picture appear?

If it has the attribute, and it appears when viewed in a browser, then I don't know why it wouldn't work in the iOS HA app. Sounds like a bug in the app to me.

**Comment by olafvdg** [comment]
Checked the `entity_picture`. It is there and URL is accessible by browser. Strange, but could indeed be a bug in iOS HA app.

**Comment by pnbruckner** [comment]
Check out https://community.home-assistant.io/t/life360-images-not-showing-on-mobile/636523. You'll see you're not the only one with this problem, but there doesn't seem to be any solution so far. You should probably check with the author of the iOS HA app.

**Comment by olafvdg** [comment]
Thank you, will do!

**Comment by pnbruckner** [comment]
If you do find a solution, I would appreciate if you could provide a link to it here. Thanks, and good luck!

**Comment by pnbruckner** [comment]
No new data.
