### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by UplandJacob** [pnbruckner/ha-life360#31]
Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 13:19:51 (4 occurrences)
Last logged: 13:19:51

LENGTH_FEET was used from life360, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.FEET instead, please report it to the author of the 'life360' custom integration
LENGTH_KILOMETERS was used from life360, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please report it to the author of the 'life360' custom integration
LENGTH_METERS was used from life360, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please report it to the author of the 'life360' custom integration
LENGTH_MILES was used from life360, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead, please report it to the author of the 'life360' custom integration

**Comment by pnbruckner** [comment]
0.5.2 or earlier really don't work anymore. You need to use the latest beta (0.5.3b2), but even that doesn't work for some anymore. The API keeps changing and breaking this integration.

**Comment by smarthomefamilyverrips** [comment]
> 0.5.2 or earlier really don't work anymore. You need to use the latest beta (0.5.3b2), but even that doesn't work for some anymore. The API keeps changing and breaking this integration.

@pnbruckner at me after updating from HA 2024.6.X to 2024.7.X it is working fine again for over two weeks now on V0.5.3b1

**Comment by pnbruckner** [comment]
Yes, it seems something changed in 2024.7 that allows this to work again. The only thing I can think of is somehow the TLS fingerprint changed such that Cloudflare is no longer blocking our usage of the Life360 API. If so, then this could stop working again at any moment. I have no way to know.

**Comment by smarthomefamilyverrips** [comment]
> Yes, it seems something changed in 2024.7 that allows this to work again. The only thing I can think of is somehow the TLS fingerprint changed such that Cloudflare is no longer blocking our usage of the Life360 API. If so, then this could stop working again at any moment. I have no way to know.

Well let's hope it keeps working 😉

**Comment by pnbruckner** [comment]
@UplandJacob, closing since you haven't responded. Try upgrading to the latest version (which is now 0.5.3.) If you still have problems, either reopen this issue or open a new one.

**Comment by UplandJacob** [comment]
It was just a deprecation warning, but I haven't seen it on the latest version so all good
