### ISSUE TITLE
Locations not updating

### ISSUE THREAD

**Issue by mversion** [pnbruckner/ha-life360#33]
For a little while now, my family's location is stuck at either work or school. Today I noticed my location was stuck at work, but once I opened the Life360 app on my phone, it updated to the correct location in HA.

On the latest version of both HA and the Life360 integration.

**Comment by pnbruckner** [comment]
> On the latest version of both HA and the Life360 integration.

Please be more specific. There are multiple LIfe360 integrations, and beta versions as well as fully released versions. I can't guess what you're using.

**Comment by mversion** [comment]
Sorry, I must be misunderstanding something. I have what I believe is your integration installed: https://github.com/pnbruckner/ha-life360 
Version: 0.5.3 via HACS. I've also just upgraded Home Assistant to version 2024.9.1.

Non-verified Life360 account.

**Comment by acato** [comment]
Same issue on version 0.5.3 via HACS on HA 2024.9.1 - verified Life360 account and authentication via token.

**Comment by Likaybai** [comment]
I have no issue here using the latest HA and 0.5.3 Life360 version.

**Comment by acato** [comment]
**RESOLVED** - in the logs I found the updates were rejected because the GPS resolution declared was greater that what I had set in the configuration (15 instead of 10). Bumping the GPS resolution to 30 in the configuration solved the problem.

**Comment by pnbruckner** [comment]
@mversion thanks for the additional detail.

The symptoms you describe sound like a Life360 app issue on your device(s.) I.e., it's not updating in the background like it should. Note that when anyone in the Circle opens the Life360 app on their device, _all_ the Members in that Circle will update their locations "on demand." This can also be initiated via the HA integration using the [`life360.update_location`](https://github.com/pnbruckner/ha-life360#life360update_location) service.

I would recommend reading Life360's FAQs to make sure your device or devices are running the Life360 app optimally and updating in the background.

Also note what @acato posted just above. It's possible the device apps are updating in the background, but with an accuracy that doesn't meet the threshold you set in the HA integration.
