### ISSUE TITLE
Enabling account after error doesn't work since installing HA 2024.11

### ISSUE THREAD

**Issue by andrewcliffoutlook** [pnbruckner/ha-life360#36]
If Life360 becomes disabled I am not able to successfully enable again without restarting HA.  This has started happening since updating to HA 2024.11.  The error message being logged is as follows:

Logger: homeassistant
Source: helpers/frame.py:154
First occurred: 10:45:34 (1 occurrences)
Last logged: 10:45:34

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 148, in report
    integration_frame = get_integration_frame(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 108, in get_integration_frame
    raise MissingIntegrationFrame
homeassistant.helpers.frame.MissingIntegrationFrame

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/life360/__init__.py", line 104, in async_process_data
    await asyncio.gather(*coros)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in async_config_entry_first_refresh
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 154, in report
    raise RuntimeError(msg) from err
RuntimeError: Detected code that uses `async_config_entry_first_refresh`, which is only supported when entry state is ConfigEntryState.SETUP_IN_PROGRESS, but it is in state ConfigEntryState.LOADED, This will stop working in Home Assistant 2025.11. Please report this issue.

**Comment by pnbruckner** [comment]
Thanks. Already working on a fix: #35.

**Comment by pnbruckner** [comment]
@andrewcliffoutlook, please try 0.5.4b0 and let me know if it resolves the problem for you.

**Comment by andrewcliffoutlook** [comment]
@pnbruckner I have had 0.5.4b0 installed for 2 days now and since then I haven't had the Life360 integration go into an error/repair condition whereas this was happening daily and requiring a reboot to fix after re-enabling the account so it appears to have fixed it.  Will let you know if there are any issues should the it go into an error/repair state.

**Comment by andrewcliffoutlook** [comment]
It was 0.5.3

Kind regards

Andrew Cliff

Sent from my phone

On 13 Nov 2024, at 14:41, Phil Bruckner ***@***.***> wrote:

﻿

@andrewcliffoutlook<https://github.com/andrewcliffoutlook> do you know what integration version you were using before upgrading to 0.5.4b0? I'm curious, because I wouldn't think you should have experienced the disabling issue (especially daily) with relatively newer versions.
