### ISSUE TITLE
Location not updating

### ISSUE THREAD

**Issue by r4zi3lrrr** [pnbruckner/ha-life360#38]
Hi,

I'm fairly new to HA (VM version) so please be gentle. :)

I've unverified my account from Life360 so that it only logs in with username + password and the Life360 Integration has added members of my Circle but it doesn't seem to update their location.

Come to mention where should I be looking for members of my circle, I'm just using the HA location - hopefully, that's correct.

Any help would be much appreciated as we're all running Life360 and it seems to give a good indication as to where everyone is.

I'm running HA 2024.11.2
Life360 Integration version 0.3.10

**Comment by pnbruckner** [comment]
@r4zi3lrrr you are using a very old version of this integration which is not expected to work anymore due to changes in Life360's API. Please update to the latest version (0.5.4) and try again. You may have to recreate the config entries.

**Comment by pnbruckner** [comment]
@drewlukac what version of this integration and HA are you using? Have you set a "Max GPS accuracy", and if so, to what value? Also, see #37.

**Comment by r4zi3lrrr** [comment]
> @r4zi3lrrr you are using a very old version of this integration which is not expected to work anymore due to changes in Life360's API. Please update to the latest version (0.5.4) and try again. You may have to recreate the config entries.

Sorry how best to update my current version?

**Comment by r4zi3lrrr** [comment]
> @r4zi3lrrr you are using a very old version of this integration which is not expected to work anymore due to changes in Life360's API. Please update to the latest version (0.5.4) and try again. You may have to recreate the config entries.

Thank you, the newer version of the integration looks promising and updated my circle pretty much straight away - luckily I didn't need to recreate the config entries. 

Appreciate the support.

**Comment by drewlukac** [comment]
> @drewlukac what version of this integration and HA are you using? Have you set a "Max GPS accuracy", and if so, to what value? Also, see #37.

running 0.5.4 w/ Max GPS accuracy set to 3

**Comment by pnbruckner** [comment]
@drewlukac that's probably your problem. Try setting it higher to like 100, or at least 25. Any updates with an accuracy of higher than 3 are being rejected. (Higher numbers are _less_ accurate.)
