### ISSUE TITLE
life360 entity user image error

### ISSUE THREAD

**Issue by d4nm0** [pnbruckner/ha-life360#42]
The image is displayed on a computer but on the Home Assistant mobile application there is an error the image is not displayed.

entity name : device_tracker.life360_dan_monceau

ha app : 
![image0](https://github.com/user-attachments/assets/159e6c0b-92a2-4e24-98bc-493fb543ec08)

ha webpage : 
![image](https://github.com/user-attachments/assets/84b62d5b-3de9-4eef-aad2-e9148b3388a0)

**Comment by pnbruckner** [comment]
Are you running the HA mobile app on Android or iOS? If the latter, check out: #27

**Comment by d4nm0** [comment]
ah yes thank you, ugly picture :0
