### ISSUE TITLE
500 error then cannot setup after deleting integration

### ISSUE THREAD

**Issue by bkr1969** [pnbruckner/ha-life360#5]
No matter what I use for username and password, I get "Invalid authentication."

**Comment by pnbruckner** [comment]
Yes, same problem with the built-in integration. Seems Life360 has changed the (undocumented & unsupported) API again. I think this is the end of a Life360 integration for HA (built-in or custom), unless someone figures out what to do. I can't, sorry.

**Comment by bkr1969** [comment]
Life360 has become a pain.

**Comment by MikeGuest** [comment]
If that's the case, then please accept my thanks for all the use i've had from it in the last couple of years. This is always a possibility with an unauthorised API

Is there a way to temporarily disable the integration so as not to be a nuisance to the company by making failed API calls until such time as a solution is found (if ever)?

**Comment by pnbruckner** [comment]
Go to the Integrations page. Ignore the box that says it needs to be reauthenticate. Find the "normal" Life360 integration box below that. Click on it. Click on the three-dot menu and disable or delete it.

**Comment by pnbruckner** [comment]
@MikeGuest 

> Is there still a file on my storage that might list all my zone information? that would help a lot in setting up zones within HA

If you mean what the life360 integration writes to the log when debug is enabled? The only place that exists is in the log. If you've deleted/overwritten them, then it's gone. But, HA keeps a back log in home-assisant.log.1, so maybe you can look in there if it's still around and hasn't been overwritten by restarts.

**Comment by pnbruckner** [comment]
A fix has been determined, at least for now. Who knows when it will break again. I'll make a new release shortly...
