### ISSUE TITLE
ha-life360 was add but the status is still unknown

### ISSUE THREAD

**Issue by eyal38** [pnbruckner/ha-life360#6]
hi i have add your code to config\custom_components\life360

same as my other custom_components

the error i had on life 360 (authorization) is gone now 
but the status of the device_tracker is unavailable

device_tracker.eyal | unavailable

the : binary_sensor.life360_online_xxxxx_gmail_com   is disconnected

Core
2023.12.3
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2

**Comment by Das-Kittylein** [comment]
Der Fehler, den ich auf das 360 (Autorisierung) hatte, ist jetzt weg
aber der Status des Gerätes -tracker ist nicht verfügbar

device-tracker.eyal | nicht verfügbar

**Comment by pnbruckner** [comment]
@eyal38 what version of this custom integration do you have? Do you have a folder named life360 directly in your configuration folder? Are you using your phone number or email address for your life360 username?

**Comment by pnbruckner** [comment]
@Das-Kittylein Englisch Bitte

**Comment by eyal38** [comment]
*what version of this custom integration do you have?*
pnbruckner
<https://github.com/pnbruckner/ha-life360/commits?author=pnbruckner> Bump
version to 0.3.10
<https://github.com/pnbruckner/ha-life360/commit/667a7ee0ebe3ebf47a996849eb550cbbe30225bf>
*Do you have a folder named life360 directly in your configuration folder*
[image: image.png]


yes


* Are you using your phone number or email address for your life360
username*
email address


‫בתאריך יום א׳, 24 בדצמ׳ 2023 ב-21:41 מאת ‪Phil Bruckner‬‏ <‪
***@***.***‬‏>:‬

**Comment by pnbruckner** [comment]
@eyal38 you need to delete the folder named life360 that is directly in your configuration folder.  The one in `custom_compents` is ok.

**Comment by eyal38** [comment]
Sorry I was missed understood
I have life360 folder only under the custom components

בתאריך יום ב׳, 25 בדצמ׳ 2023, 21:10, מאת Phil Bruckner ‏<
***@***.***>:

**Comment by mschut** [comment]
Unfortunately I still have the login error. I have uninstalled the extension completely, reset my password, but still get the error "Invalid authentication". 

Just a thought, I don't have a paid account, would that be a difference?

**Comment by DanAaen** [comment]
> Unfortunately I still have the login error. I have uninstalled the extension completely, reset my password, but still get the error "Invalid authentication".
> 
> Just a thought, I don't have a paid account, would that be a difference?

I have the same issue. With a paid account

**Comment by pnbruckner** [comment]
The only suggestions I can make are to change your life360 password, do NOT verify your phone number, and try again.

**Comment by mschut** [comment]
> The only suggestions I can make are to change your life360 password, do NOT verify your phone number, and try again.

Did that (not the phon verification), unfortunately no improvement

**Comment by DanAaen** [comment]
Finally got Life360 working again.
1. Removed (deleted) standard life360 integration.
2. Removed (deleted) custom life360 integration in HACS.
3. Deleted folder config\custom_components\life360.
4. Restarted HA.
5. With my life360 changed password (same email address).
6. Added custom life360 integration in HACS.
7. Restarted HA.
8. Added life360 standard integration with old user and new password (success).
9. Restarted HA, now all entities were back.
Big thanks @pnbruckner !

**Comment by pnbruckner** [comment]
@DanAaen you should not need to use the custom version of the life360 integration (ha-life360). Just upgrading to 2023.12.4 and using the built-in life360 integration should work.

BTW, "removing/deleting" the standard life360 integration is really a misnomer. You're actually just deleting a config entry for the integration. In fact, whether you use the standard (aka built-in) integration, or the custom one (ha-life360), the same config entry is used. So, e.g., if/when you now remove the custom integration (via HACS, which should also remove the `custom_components/life360` folder, too), you shouldn't have to make any changes on the Integrations page.

**Comment by pnbruckner** [comment]
@eyal38 did you get the life360 integration working again, either this custom one, or the standard, built-in one?

**Comment by eyal38** [comment]
my life360 integration has just come back to life :) thanks allot

‫בתאריך שבת, 30 בדצמ׳ 2023 ב-15:52 מאת ‪Phil Bruckner‬‏ <‪
***@***.***‬‏>:‬

**Comment by eyal38** [comment]
all work fine now

my workaround was:

remove the official life360 integration.
update the password for the integration.
reinstall the integration with the new password 
(i didn't remove the ha-360 configuration)
