### ISSUE TITLE
Invalid Authorisation is back

### ISSUE THREAD

**Issue by matthewharrington** [pnbruckner/ha-life360#7]
Hi team.

I came across your branch a couple of days ago and successfully installed it and have been running it with no problems. I got kicked out in the integration tonight and now get Invalid Authorisation error again. I see there is no opportunity in the app to even enter a password anymore and it appears to be all done byMFA.

Many thanks for your hard work on keeping this going.

**Comment by SalvatoreITA** [comment]
I too have the same problem since this morning

**Comment by SalvatoreITA** [comment]
This morning it also gave me authentication problems, I solved it like this: 

I installed the latest version of the component

I changed the Life 360 password

 Restarted Home Assistant

Reconfigure Life 360 ​​on home assistant

 And it started again

**Comment by pnbruckner** [comment]
@matthewharrington are you using 0.3.10? Are you using phone number or email for life360 username in HA?

**Comment by matthewharrington** [comment]
I have been using the email address. A password reset has me back in. Thank @SalvatoreITA
