### ISSUE TITLE
Again problem authentication

### ISSUE THREAD

**Issue by SalvatoreITA** [pnbruckner/ha-life360#8]
Hi, I've been disconnected from my Life360 account again, I log in with my email address, I've changed my Life password again, HA has restarted, but it doesn't connect in any way, it tells me authentication failed.

**Comment by garagara93** [comment]
Same here. I have the custom integration by @pnbruckner

**Comment by fcocarmona** [comment]
Same, after reboot hole system, change the life password, restart ha, try to reconnect life in HA  it says "authentication fail"

**Comment by riddik14** [comment]
Same here. Release version and beta

**Comment by pnbruckner** [comment]
I can confirm it is broken again. Life360 seems to possibly be trying to actively block use cases outside their official app (via Cloudflare, etc.) It appears it's time to give up.

**Comment by DanAaen** [comment]
Well that's really inconvenient.
I'm really happy with both 360life and HA.
Best alternative ?
Thanks for your contribution.

**Comment by pnbruckner** [comment]
I personally use https://www.home-assistant.io/integrations/google_maps/. It's old, but it seems to work. And, BTW, the doc talks about creating a separate account to use the integration. You, of course, can do that, but it's not necessary. The trick is capturing the cookies file.

**Comment by SalvatoreITA** [comment]
> Personalmente utilizzo https://www.home-assistant.io/integrations/google_maps/ . È vecchio, ma sembra funzionare. E, a proposito, il documento parla della creazione di un account separato per utilizzare l'integrazione. Ovviamente puoi farlo, ma non è necessario. Il trucco sta nel catturare il file dei cookie.

Does it consume as much battery compared to Life?

**Comment by pnbruckner** [comment]
I believe I already answered your question in a PM on the community forum.

**Comment by SalvatoreITA** [comment]
> I believe I already answered your question in a PM on the community forum.

yes I saw it now, sorry

**Comment by garagara93** [comment]
is it working again? At the moment seems to be ok!

**Comment by pnbruckner** [comment]
@garagara93 a few people have said, after it appeared that Life360 had begun purposely trying to lock out unauthorized usage of their server, that it still worked for them. But I've only heard that a few times, and last time I tried, it still didn't. I supposed I could give it a try again, but even if it is working, I wouldn't hold out hope it will continue to do so for a significant amount of time.
